#ifndef CONFIG_H
#define CONFIG_H

#define WEATHER_API_KEY "YOUR API KEY HERE"
#define GOOGLE_API_CUSTOM_SEARCH_KEY "YOUR API KEY HERE"
#define GOOGLE_API_GEOCODING_KEY "YOUR API KEY HERE"
#define GOOGLE_CUSTOM_SEARCH_CX "YOUR API KEY HERE"
#define VERSION "1.0"
#define BOTNAME "qwerty"
#define CODENAME "Test"

#endif // CONFIG_H
